server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/xml
      - text/plain
spring:
  application:
    name: api-tarefa
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tarefadb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER_NAME:root}
    password: ${DATABASE_USER_PASSWORD:root}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect